baseURL = 'http://gabrielkp.github.io'
languageCode = 'en-us'
title = 'Gabriel Kressin Palacios'
theme = 'devise'
relativeURLs = true
enableEmoji = true
copyright = "&copy; 2023, Gabriel Kressin Palacios"


# Main menu items
[menu]
  [[menu.main]]
    identifier = "posters"
    name = "Posters"
    title = "Posters"
    url = "/posters/"
    weight = -110

# Configuration Features
[params]
  description = "Personal Website | Gabriel Kressin Palacios"      # Your meta description of the site
  header_title = "Gabriel Kressin Palacios"                 # Your header title
  header_subtitle = "What are the algorithms of the mind?" # Your header subtitle
  home_image = "/headshot.sq.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/gabrielkp"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/gabrielkressin/"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
